dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean install
  - mvn cobertura:cobertura
after_success:
- mvn clean cobertura:cobertura coveralls:report